version: "3"  # Double quotes are preferred for version

services:
  auth-db:  # Service names should be lowercase with hyphens
    image: postgres:16.2
    container_name: auth-db
    restart: always  # "aways" is a typo, use "always"
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456  # Consider using a stronger password
    ports:
      - 5432:5432  # Correct port mapping

  product-db:
    image: postgres:16.2
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456  # Consider using a stronger password
    ports:
      - 5433:5432  # Double-check if this is intended port mapping

  sales-db:
    image: mongo:latest
    container_name: sales-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456  # Consider using a stronger password
    ports:
      - 27019:27017  # This port is already in use by another service, consider a different one
      - 28017:28017  # Optional port, can be removed if not needed

  sales-rabbit:
    image: rabbitmq:3-management
    container_name: sales-rabbit
    restart: always
    depends_on:
      - sales-db  # Depends on service name, not container name
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672

